# Generated by Django 5.1.3 on 2024-12-14 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectify', '0003_alter_profile_profile_picture_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    migrations.AlterField(
    model_name='profile',
    name='bio',
    field=models.CharField(max_length=255, null=True, blank=True, default=''),
),
migrations.AlterField(
    model_name='profile',
    name='profile_picture',
    field=models.ImageField(null=True, blank=True, default=None, upload_to='profile_pics/'),
),
